### ISSUE TITLE
Create belt subsystem

### ISSUE THREAD

**Issue by awordforthat** [frc2423/2022#20]

**Comment by Wheeleral** [comment]
- Stop
- forward
- reverse
-  run_storage function
    void run_storage(){
       if (intake.isDown() || shoorter.isShoot() || Devices.controller.getButton) runfoward()
       else if Devices.controller.getOtherButton runreverse
        else stop

   }

**Comment by Wheeleral** [comment]
Pretty much remove all instances of belt outside of this class and then call run_storage in robot
