### ISSUE TITLE
Get 0, 1, 2, auto modes working

### ISSUE THREAD

**Issue by awordforthat** [frc2423/2022#23]

**Comment by Wheeleral** [comment]
- Check velocities and accelerations --- fix units as needed
- Make sure in 1 and 2 ball it taxi backs
- 2 ball auto - get middle and top positions completely correct
- 2 ball auto - make sure it's against the fender for shooting---- depends on if using high/low goal

**Comment by Wheeleral** [comment]
All-change shooter speed
0 ball- change taxi distance?
1 ball- change taxi distance?
2 ball- change cargo to hub ending to back of tarmac
        - need to check if we need different code for the different positions if we are shooting from the back of the tarmac
